Public Class FORM4_SEMBILAN

    Public Sub Form4_sembilan_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Randomize()
        Timer1_sembilan.Enabled = True

        For i = 0 To 8
            For y = 0 To 8
                sembilan(i, y) = New Button
                sembilan(i, y).Top = 30 + i * 40
                sembilan(i, y).Left = 30 + y * 40
                sembilan(i, y).Size = New Size(40, 40)
                sembilan(i, y).Name = i & "_" & y

                If i < 3 And y > 5 Then
                    sembilan(i, y).BackColor = Color.AliceBlue
                ElseIf i < 3 And y > 2 Then
                    sembilan(i, y).BackColor = Color.Beige
                ElseIf i < 3 And y >= 0 Then
                    sembilan(i, y).BackColor = Color.AliceBlue
                ElseIf i < 6 And y > 5 Then
                    sembilan(i, y).BackColor = Color.Beige
                ElseIf i < 6 And y > 2 Then
                    sembilan(i, y).BackColor = Color.AliceBlue
                ElseIf i < 6 And y >= 0 Then
                    sembilan(i, y).BackColor = Color.Beige
                ElseIf i < 10 And y > 5 Then
                    sembilan(i, y).BackColor = Color.AliceBlue
                ElseIf i < 10 And y > 2 Then
                    sembilan(i, y).BackColor = Color.Beige
                ElseIf i < 10 And y >= 0 Then
                    sembilan(i, y).BackColor = Color.AliceBlue
                End If

                Me.Controls.Add(sembilan(i, y))

                AddHandler sembilan(i, y).Click, AddressOf isiangka
                AddHandler sembilan(i, y).Click, AddressOf checkcolumn9
                AddHandler sembilan(i, y).Click, AddressOf checkrow9
                AddHandler sembilan(i, y).Click, AddressOf checkotak9
                AddHandler sembilan(i, y).Click, AddressOf hitungsalah
                AddHandler sembilan(i, y).Click, AddressOf win9
                AddHandler sembilan(i, y).Click, AddressOf autochecksembilan1
                AddHandler sembilan(i, y).Click, AddressOf autochecksembilan2
                AddHandler sembilan(i, y).Click, AddressOf autochecksembilan3
                AddHandler sembilan(i, y).Click, AddressOf changecolor9
            Next
        Next

        AddHandler Bttn_GiveUp.Click, AddressOf win9
        AddHandler Bttn_Hint.Click, AddressOf win9

        sembilanQQ = Rnd() * 9 + 1

        If sembilanQQ = 1 Then
            sembilan(0, 0).Text = "6"
            sembilan(0, 1).Text = "3"
            sembilan(0, 2).Text = "5"
            sembilan(0, 3).Text = "2"
            sembilan(0, 4).Text = "9"
            sembilan(0, 5).Text = "4"
            sembilan(0, 6).Text = "7"
            sembilan(0, 7).Text = "1"
            sembilan(0, 8).Text = "8"
            sembilan(1, 0).Text = "7"
            sembilan(1, 1).Text = "9"
            sembilan(1, 2).Text = "1"
            sembilan(1, 3).Text = "6"
            sembilan(1, 4).Text = "5"
            sembilan(1, 5).Text = "8"
            sembilan(1, 6).Text = "3"
            sembilan(1, 7).Text = "2"
            sembilan(1, 8).Text = "4"
            sembilan(2, 0).Text = "4"
            sembilan(2, 1).Text = "2"
            sembilan(2, 2).Text = "8"
            sembilan(2, 3).Text = "7"
            sembilan(2, 4).Text = "3"
            sembilan(2, 5).Text = "1"
            sembilan(2, 6).Text = "5"
            sembilan(2, 7).Text = "9"
            sembilan(2, 8).Text = "6"
            sembilan(3, 0).Text = "2"
            sembilan(3, 1).Text = "7"
            sembilan(3, 2).Text = "9"
            sembilan(3, 3).Text = "8"
            sembilan(3, 4).Text = "4"
            sembilan(3, 5).Text = "6"
            sembilan(3, 6).Text = "1"
            sembilan(3, 7).Text = "3"
            sembilan(3, 8).Text = "5"
            sembilan(4, 0).Text = "1"
            sembilan(4, 1).Text = "8"
            sembilan(4, 2).Text = "6"
            sembilan(4, 3).Text = "3"
            sembilan(4, 4).Text = "7"
            sembilan(4, 5).Text = "5"
            sembilan(4, 6).Text = "2"
            sembilan(4, 7).Text = "4"
            sembilan(4, 8).Text = "9"
            sembilan(5, 0).Text = "3"
            sembilan(5, 1).Text = "5"
            sembilan(5, 2).Text = "4"
            sembilan(5, 3).Text = "9"
            sembilan(5, 4).Text = "1"
            sembilan(5, 5).Text = "2"
            sembilan(5, 6).Text = "8"
            sembilan(5, 7).Text = "6"
            sembilan(5, 8).Text = "7"
            sembilan(6, 0).Text = "5"
            sembilan(6, 1).Text = "1"
            sembilan(6, 2).Text = "2"
            sembilan(6, 3).Text = "4"
            sembilan(6, 4).Text = "8"
            sembilan(6, 5).Text = "9"
            sembilan(6, 6).Text = "6"
            sembilan(6, 7).Text = "7"
            sembilan(6, 8).Text = "3"
            sembilan(7, 0).Text = "9"
            sembilan(7, 1).Text = "6"
            sembilan(7, 2).Text = "3"
            sembilan(7, 3).Text = "5"
            sembilan(7, 4).Text = "2"
            sembilan(7, 5).Text = "7"
            sembilan(7, 6).Text = "4"
            sembilan(7, 7).Text = "8"
            sembilan(7, 8).Text = "1"
            sembilan(8, 0).Text = "8"
            sembilan(8, 1).Text = "4"
            sembilan(8, 2).Text = "7"
            sembilan(8, 3).Text = "1"
            sembilan(8, 4).Text = "6"
            sembilan(8, 5).Text = "3"
            sembilan(8, 6).Text = "9"
            sembilan(8, 7).Text = "5"
            sembilan(8, 8).Text = "2"

        ElseIf sembilanQQ = 2 Then
            sembilan(0, 0).Text = "1"
            sembilan(0, 1).Text = "2"
            sembilan(0, 2).Text = "5"
            sembilan(0, 3).Text = "4"
            sembilan(0, 4).Text = "8"
            sembilan(0, 5).Text = "3"
            sembilan(0, 6).Text = "6"
            sembilan(0, 7).Text = "9"
            sembilan(0, 8).Text = "7"
            sembilan(1, 0).Text = "7"
            sembilan(1, 1).Text = "4"
            sembilan(1, 2).Text = "8"
            sembilan(1, 3).Text = "1"
            sembilan(1, 4).Text = "6"
            sembilan(1, 5).Text = "9"
            sembilan(1, 6).Text = "2"
            sembilan(1, 7).Text = "3"
            sembilan(1, 8).Text = "5"
            sembilan(2, 0).Text = "9"
            sembilan(2, 1).Text = "6"
            sembilan(2, 2).Text = "3"
            sembilan(2, 3).Text = "2"
            sembilan(2, 4).Text = "5"
            sembilan(2, 5).Text = "7"
            sembilan(2, 6).Text = "4"
            sembilan(2, 7).Text = "1"
            sembilan(2, 8).Text = "8"
            sembilan(3, 0).Text = "4"
            sembilan(3, 1).Text = "3"
            sembilan(3, 2).Text = "7"
            sembilan(3, 3).Text = "8"
            sembilan(3, 4).Text = "2"
            sembilan(3, 5).Text = "1"
            sembilan(3, 6).Text = "5"
            sembilan(3, 7).Text = "6"
            sembilan(3, 8).Text = "9"
            sembilan(4, 0).Text = "8"
            sembilan(4, 1).Text = "5"
            sembilan(4, 2).Text = "6"
            sembilan(4, 3).Text = "9"
            sembilan(4, 4).Text = "3"
            sembilan(4, 5).Text = "4"
            sembilan(4, 6).Text = "1"
            sembilan(4, 7).Text = "7"
            sembilan(4, 8).Text = "2"
            sembilan(5, 0).Text = "2"
            sembilan(5, 1).Text = "1"
            sembilan(5, 2).Text = "9"
            sembilan(5, 3).Text = "6"
            sembilan(5, 4).Text = "7"
            sembilan(5, 5).Text = "5"
            sembilan(5, 6).Text = "8"
            sembilan(5, 7).Text = "4"
            sembilan(5, 8).Text = "3"
            sembilan(6, 0).Text = "5"
            sembilan(6, 1).Text = "8"
            sembilan(6, 2).Text = "4"
            sembilan(6, 3).Text = "3"
            sembilan(6, 4).Text = "9"
            sembilan(6, 5).Text = "6"
            sembilan(6, 6).Text = "7"
            sembilan(6, 7).Text = "2"
            sembilan(6, 8).Text = "1"
            sembilan(7, 0).Text = "6"
            sembilan(7, 1).Text = "9"
            sembilan(7, 2).Text = "2"
            sembilan(7, 3).Text = "7"
            sembilan(7, 4).Text = "1"
            sembilan(7, 5).Text = "8"
            sembilan(7, 6).Text = "3"
            sembilan(7, 7).Text = "5"
            sembilan(7, 8).Text = "4"
            sembilan(8, 0).Text = "3"
            sembilan(8, 1).Text = "7"
            sembilan(8, 2).Text = "1"
            sembilan(8, 3).Text = "5"
            sembilan(8, 4).Text = "4"
            sembilan(8, 5).Text = "2"
            sembilan(8, 6).Text = "9"
            sembilan(8, 7).Text = "8"
            sembilan(8, 8).Text = "6"

        ElseIf sembilanQQ = 3 Then
            sembilan(0, 0).Text = "2"
            sembilan(0, 1).Text = "7"
            sembilan(0, 2).Text = "4"
            sembilan(0, 3).Text = "3"
            sembilan(0, 4).Text = "8"
            sembilan(0, 5).Text = "5"
            sembilan(0, 6).Text = "6"
            sembilan(0, 7).Text = "1"
            sembilan(0, 8).Text = "9"
            sembilan(1, 0).Text = "9"
            sembilan(1, 1).Text = "3"
            sembilan(1, 2).Text = "2"
            sembilan(1, 3).Text = "8"
            sembilan(1, 4).Text = "6"
            sembilan(1, 5).Text = "1"
            sembilan(1, 6).Text = "7"
            sembilan(1, 7).Text = "5"
            sembilan(1, 8).Text = "4"
            sembilan(2, 0).Text = "1"
            sembilan(2, 1).Text = "6"
            sembilan(2, 2).Text = "5"
            sembilan(2, 3).Text = "7"
            sembilan(2, 4).Text = "4"
            sembilan(2, 5).Text = "9"
            sembilan(2, 6).Text = "3"
            sembilan(2, 7).Text = "2"
            sembilan(2, 8).Text = "8"
            sembilan(3, 0).Text = "3"
            sembilan(3, 1).Text = "5"
            sembilan(3, 2).Text = "9"
            sembilan(3, 3).Text = "8"
            sembilan(3, 4).Text = "7"
            sembilan(3, 5).Text = "2"
            sembilan(3, 6).Text = "4"
            sembilan(3, 7).Text = "6"
            sembilan(3, 8).Text = "1"
            sembilan(4, 0).Text = "8"
            sembilan(4, 1).Text = "4"
            sembilan(4, 2).Text = "6"
            sembilan(4, 3).Text = "1"
            sembilan(4, 4).Text = "5"
            sembilan(4, 5).Text = "3"
            sembilan(4, 6).Text = "2"
            sembilan(4, 7).Text = "9"
            sembilan(4, 8).Text = "7"
            sembilan(5, 0).Text = "7"
            sembilan(5, 1).Text = "2"
            sembilan(5, 2).Text = "1"
            sembilan(5, 3).Text = "6"
            sembilan(5, 4).Text = "9"
            sembilan(5, 5).Text = "4"
            sembilan(5, 6).Text = "8"
            sembilan(5, 7).Text = "3"
            sembilan(5, 8).Text = "5"
            sembilan(6, 0).Text = "4"
            sembilan(6, 1).Text = "8"
            sembilan(6, 2).Text = "3"
            sembilan(6, 3).Text = "5"
            sembilan(6, 4).Text = "1"
            sembilan(6, 5).Text = "6"
            sembilan(6, 6).Text = "9"
            sembilan(6, 7).Text = "7"
            sembilan(6, 8).Text = "2"
            sembilan(7, 0).Text = "6"
            sembilan(7, 1).Text = "1"
            sembilan(7, 2).Text = "7"
            sembilan(7, 3).Text = "9"
            sembilan(7, 4).Text = "2"
            sembilan(7, 5).Text = "8"
            sembilan(7, 6).Text = "5"
            sembilan(7, 7).Text = "4"
            sembilan(7, 8).Text = "3"
            sembilan(8, 0).Text = "5"
            sembilan(8, 1).Text = "9"
            sembilan(8, 2).Text = "2"
            sembilan(8, 3).Text = "4"
            sembilan(8, 4).Text = "3"
            sembilan(8, 5).Text = "7"
            sembilan(8, 6).Text = "1"
            sembilan(8, 7).Text = "8"
            sembilan(8, 8).Text = "6"

        ElseIf sembilanQQ = 4 Then
            sembilan(0, 0).Text = "8"
            sembilan(0, 1).Text = "5"
            sembilan(0, 2).Text = "9"
            sembilan(0, 3).Text = "3"
            sembilan(0, 4).Text = "2"
            sembilan(0, 5).Text = "4"
            sembilan(0, 6).Text = "6"
            sembilan(0, 7).Text = "1"
            sembilan(0, 8).Text = "7"
            sembilan(1, 0).Text = "4"
            sembilan(1, 1).Text = "7"
            sembilan(1, 2).Text = "3"
            sembilan(1, 3).Text = "6"
            sembilan(1, 4).Text = "9"
            sembilan(1, 5).Text = "1"
            sembilan(1, 6).Text = "2"
            sembilan(1, 7).Text = "5"
            sembilan(1, 8).Text = "8"
            sembilan(2, 0).Text = "2"
            sembilan(2, 1).Text = "1"
            sembilan(2, 2).Text = "6"
            sembilan(2, 3).Text = "5"
            sembilan(2, 4).Text = "7"
            sembilan(2, 5).Text = "8"
            sembilan(2, 6).Text = "4"
            sembilan(2, 7).Text = "3"
            sembilan(2, 8).Text = "9"
            sembilan(3, 0).Text = "5"
            sembilan(3, 1).Text = "6"
            sembilan(3, 2).Text = "2"
            sembilan(3, 3).Text = "9"
            sembilan(3, 4).Text = "3"
            sembilan(3, 5).Text = "7"
            sembilan(3, 6).Text = "1"
            sembilan(3, 7).Text = "8"
            sembilan(3, 8).Text = "4"
            sembilan(4, 0).Text = "1"
            sembilan(4, 1).Text = "9"
            sembilan(4, 2).Text = "8"
            sembilan(4, 3).Text = "2"
            sembilan(4, 4).Text = "4"
            sembilan(4, 5).Text = "5"
            sembilan(4, 6).Text = "3"
            sembilan(4, 7).Text = "7"
            sembilan(4, 8).Text = "6"
            sembilan(5, 0).Text = "7"
            sembilan(5, 1).Text = "3"
            sembilan(5, 2).Text = "4"
            sembilan(5, 3).Text = "1"
            sembilan(5, 4).Text = "8"
            sembilan(5, 5).Text = "6"
            sembilan(5, 6).Text = "5"
            sembilan(5, 7).Text = "9"
            sembilan(5, 8).Text = "2"
            sembilan(6, 0).Text = "6"
            sembilan(6, 1).Text = "8"
            sembilan(6, 2).Text = "5"
            sembilan(6, 3).Text = "7"
            sembilan(6, 4).Text = "1"
            sembilan(6, 5).Text = "2"
            sembilan(6, 6).Text = "9"
            sembilan(6, 7).Text = "4"
            sembilan(6, 8).Text = "3"
            sembilan(7, 0).Text = "3"
            sembilan(7, 1).Text = "4"
            sembilan(7, 2).Text = "1"
            sembilan(7, 3).Text = "8"
            sembilan(7, 4).Text = "6"
            sembilan(7, 5).Text = "9"
            sembilan(7, 6).Text = "7"
            sembilan(7, 7).Text = "2"
            sembilan(7, 8).Text = "5"
            sembilan(8, 0).Text = "9"
            sembilan(8, 1).Text = "2"
            sembilan(8, 2).Text = "7"
            sembilan(8, 3).Text = "4"
            sembilan(8, 4).Text = "5"
            sembilan(8, 5).Text = "3"
            sembilan(8, 6).Text = "8"
            sembilan(8, 7).Text = "6"
            sembilan(8, 8).Text = "1"

        ElseIf sembilanQQ = 5 Then
            sembilan(0, 0).Text = "5"
            sembilan(0, 1).Text = "1"
            sembilan(0, 2).Text = "2"
            sembilan(0, 3).Text = "3"
            sembilan(0, 4).Text = "7"
            sembilan(0, 5).Text = "9"
            sembilan(0, 6).Text = "4"
            sembilan(0, 7).Text = "8"
            sembilan(0, 8).Text = "6"
            sembilan(1, 0).Text = "9"
            sembilan(1, 1).Text = "6"
            sembilan(1, 2).Text = "8"
            sembilan(1, 3).Text = "4"
            sembilan(1, 4).Text = "1"
            sembilan(1, 5).Text = "5"
            sembilan(1, 6).Text = "7"
            sembilan(1, 7).Text = "3"
            sembilan(1, 8).Text = "2"
            sembilan(2, 0).Text = "7"
            sembilan(2, 1).Text = "3"
            sembilan(2, 2).Text = "4"
            sembilan(2, 3).Text = "2"
            sembilan(2, 4).Text = "6"
            sembilan(2, 5).Text = "8"
            sembilan(2, 6).Text = "9"
            sembilan(2, 7).Text = "5"
            sembilan(2, 8).Text = "1"
            sembilan(3, 0).Text = "6"
            sembilan(3, 1).Text = "5"
            sembilan(3, 2).Text = "7"
            sembilan(3, 3).Text = "1"
            sembilan(3, 4).Text = "3"
            sembilan(3, 5).Text = "4"
            sembilan(3, 6).Text = "8"
            sembilan(3, 7).Text = "2"
            sembilan(3, 8).Text = "9"
            sembilan(4, 0).Text = "8"
            sembilan(4, 1).Text = "2"
            sembilan(4, 2).Text = "1"
            sembilan(4, 3).Text = "9"
            sembilan(4, 4).Text = "5"
            sembilan(4, 5).Text = "7"
            sembilan(4, 6).Text = "6"
            sembilan(4, 7).Text = "4"
            sembilan(4, 8).Text = "3"
            sembilan(5, 0).Text = "3"
            sembilan(5, 1).Text = "4"
            sembilan(5, 2).Text = "9"
            sembilan(5, 3).Text = "6"
            sembilan(5, 4).Text = "8"
            sembilan(5, 5).Text = "2"
            sembilan(5, 6).Text = "5"
            sembilan(5, 7).Text = "1"
            sembilan(5, 8).Text = "7"
            sembilan(6, 0).Text = "1"
            sembilan(6, 1).Text = "9"
            sembilan(6, 2).Text = "5"
            sembilan(6, 3).Text = "7"
            sembilan(6, 4).Text = "4"
            sembilan(6, 5).Text = "3"
            sembilan(6, 6).Text = "2"
            sembilan(6, 7).Text = "6"
            sembilan(6, 8).Text = "8"
            sembilan(7, 0).Text = "2"
            sembilan(7, 1).Text = "8"
            sembilan(7, 2).Text = "6"
            sembilan(7, 3).Text = "5"
            sembilan(7, 4).Text = "9"
            sembilan(7, 5).Text = "1"
            sembilan(7, 6).Text = "3"
            sembilan(7, 7).Text = "7"
            sembilan(7, 8).Text = "4"
            sembilan(8, 0).Text = "4"
            sembilan(8, 1).Text = "7"
            sembilan(8, 2).Text = "3"
            sembilan(8, 3).Text = "8"
            sembilan(8, 4).Text = "2"
            sembilan(8, 5).Text = "6"
            sembilan(8, 6).Text = "1"
            sembilan(8, 7).Text = "9"
            sembilan(8, 8).Text = "5"

        ElseIf sembilanQQ = 6 Then
            sembilan(0, 0).Text = "9"
            sembilan(0, 1).Text = "4"
            sembilan(0, 2).Text = "8"
            sembilan(0, 3).Text = "5"
            sembilan(0, 4).Text = "7"
            sembilan(0, 5).Text = "2"
            sembilan(0, 6).Text = "6"
            sembilan(0, 7).Text = "3"
            sembilan(0, 8).Text = "1"
            sembilan(1, 0).Text = "2"
            sembilan(1, 1).Text = "1"
            sembilan(1, 2).Text = "5"
            sembilan(1, 3).Text = "6"
            sembilan(1, 4).Text = "8"
            sembilan(1, 5).Text = "3"
            sembilan(1, 6).Text = "7"
            sembilan(1, 7).Text = "4"
            sembilan(1, 8).Text = "9"
            sembilan(2, 0).Text = "7"
            sembilan(2, 1).Text = "3"
            sembilan(2, 2).Text = "6"
            sembilan(2, 3).Text = "4"
            sembilan(2, 4).Text = "1"
            sembilan(2, 5).Text = "9"
            sembilan(2, 6).Text = "2"
            sembilan(2, 7).Text = "5"
            sembilan(2, 8).Text = "8"
            sembilan(3, 0).Text = "4"
            sembilan(3, 1).Text = "6"
            sembilan(3, 2).Text = "7"
            sembilan(3, 3).Text = "8"
            sembilan(3, 4).Text = "5"
            sembilan(3, 5).Text = "1"
            sembilan(3, 6).Text = "3"
            sembilan(3, 7).Text = "9"
            sembilan(3, 8).Text = "2"
            sembilan(4, 0).Text = "3"
            sembilan(4, 1).Text = "8"
            sembilan(4, 2).Text = "9"
            sembilan(4, 3).Text = "7"
            sembilan(4, 4).Text = "2"
            sembilan(4, 5).Text = "4"
            sembilan(4, 6).Text = "5"
            sembilan(4, 7).Text = "1"
            sembilan(4, 8).Text = "6"
            sembilan(5, 0).Text = "1"
            sembilan(5, 1).Text = "5"
            sembilan(5, 2).Text = "2"
            sembilan(5, 3).Text = "3"
            sembilan(5, 4).Text = "9"
            sembilan(5, 5).Text = "6"
            sembilan(5, 6).Text = "4"
            sembilan(5, 7).Text = "8"
            sembilan(5, 8).Text = "7"
            sembilan(6, 0).Text = "6"
            sembilan(6, 1).Text = "9"
            sembilan(6, 2).Text = "4"
            sembilan(6, 3).Text = "1"
            sembilan(6, 4).Text = "3"
            sembilan(6, 5).Text = "7"
            sembilan(6, 6).Text = "8"
            sembilan(6, 7).Text = "2"
            sembilan(6, 8).Text = "5"
            sembilan(7, 0).Text = "5"
            sembilan(7, 1).Text = "2"
            sembilan(7, 2).Text = "3"
            sembilan(7, 3).Text = "9"
            sembilan(7, 4).Text = "6"
            sembilan(7, 5).Text = "8"
            sembilan(7, 6).Text = "1"
            sembilan(7, 7).Text = "7"
            sembilan(7, 8).Text = "4"
            sembilan(8, 0).Text = "8"
            sembilan(8, 1).Text = "7"
            sembilan(8, 2).Text = "1"
            sembilan(8, 3).Text = "2"
            sembilan(8, 4).Text = "4"
            sembilan(8, 5).Text = "5"
            sembilan(8, 6).Text = "9"
            sembilan(8, 7).Text = "6"
            sembilan(8, 8).Text = "3"


        ElseIf sembilanQQ = 7 Then
            sembilan(0, 0).Text = "4"
            sembilan(0, 1).Text = "6"
            sembilan(0, 2).Text = "2"
            sembilan(0, 3).Text = "3"
            sembilan(0, 4).Text = "7"
            sembilan(0, 5).Text = "5"
            sembilan(0, 6).Text = "8"
            sembilan(0, 7).Text = "1"
            sembilan(0, 8).Text = "9"
            sembilan(1, 0).Text = "5"
            sembilan(1, 1).Text = "9"
            sembilan(1, 2).Text = "1"
            sembilan(1, 3).Text = "8"
            sembilan(1, 4).Text = "6"
            sembilan(1, 5).Text = "4"
            sembilan(1, 6).Text = "7"
            sembilan(1, 7).Text = "3"
            sembilan(1, 8).Text = "2"
            sembilan(2, 0).Text = "7"
            sembilan(2, 1).Text = "3"
            sembilan(2, 2).Text = "8"
            sembilan(2, 3).Text = "2"
            sembilan(2, 4).Text = "9"
            sembilan(2, 5).Text = "1"
            sembilan(2, 6).Text = "5"
            sembilan(2, 7).Text = "4"
            sembilan(2, 8).Text = "6"
            sembilan(3, 0).Text = "9"
            sembilan(3, 1).Text = "4"
            sembilan(3, 2).Text = "7"
            sembilan(3, 3).Text = "6"
            sembilan(3, 4).Text = "3"
            sembilan(3, 5).Text = "8"
            sembilan(3, 6).Text = "1"
            sembilan(3, 7).Text = "2"
            sembilan(3, 8).Text = "5"
            sembilan(4, 0).Text = "1"
            sembilan(4, 1).Text = "2"
            sembilan(4, 2).Text = "6"
            sembilan(4, 3).Text = "5"
            sembilan(4, 4).Text = "4"
            sembilan(4, 5).Text = "7"
            sembilan(4, 6).Text = "9"
            sembilan(4, 7).Text = "8"
            sembilan(4, 8).Text = "3"
            sembilan(5, 0).Text = "3"
            sembilan(5, 1).Text = "8"
            sembilan(5, 2).Text = "5"
            sembilan(5, 3).Text = "9"
            sembilan(5, 4).Text = "1"
            sembilan(5, 5).Text = "2"
            sembilan(5, 6).Text = "4"
            sembilan(5, 7).Text = "6"
            sembilan(5, 8).Text = "7"
            sembilan(6, 0).Text = "6"
            sembilan(6, 1).Text = "5"
            sembilan(6, 2).Text = "4"
            sembilan(6, 3).Text = "7"
            sembilan(6, 4).Text = "8"
            sembilan(6, 5).Text = "3"
            sembilan(6, 6).Text = "2"
            sembilan(6, 7).Text = "9"
            sembilan(6, 8).Text = "1"
            sembilan(7, 0).Text = "2"
            sembilan(7, 1).Text = "1"
            sembilan(7, 2).Text = "9"
            sembilan(7, 3).Text = "4"
            sembilan(7, 4).Text = "5"
            sembilan(7, 5).Text = "6"
            sembilan(7, 6).Text = "3"
            sembilan(7, 7).Text = "7"
            sembilan(7, 8).Text = "8"
            sembilan(8, 0).Text = "8"
            sembilan(8, 1).Text = "7"
            sembilan(8, 2).Text = "3"
            sembilan(8, 3).Text = "1"
            sembilan(8, 4).Text = "2"
            sembilan(8, 5).Text = "9"
            sembilan(8, 6).Text = "6"
            sembilan(8, 7).Text = "5"
            sembilan(8, 8).Text = "4"

        ElseIf sembilanQQ = 8 Then
            sembilan(0, 0).Text = "2"
            sembilan(0, 1).Text = "6"
            sembilan(0, 2).Text = "5"
            sembilan(0, 3).Text = "4"
            sembilan(0, 4).Text = "7"
            sembilan(0, 5).Text = "1"
            sembilan(0, 6).Text = "8"
            sembilan(0, 7).Text = "9"
            sembilan(0, 8).Text = "3"
            sembilan(1, 0).Text = "4"
            sembilan(1, 1).Text = "8"
            sembilan(1, 2).Text = "1"
            sembilan(1, 3).Text = "3"
            sembilan(1, 4).Text = "9"
            sembilan(1, 5).Text = "6"
            sembilan(1, 6).Text = "7"
            sembilan(1, 7).Text = "2"
            sembilan(1, 8).Text = "5"
            sembilan(2, 0).Text = "3"
            sembilan(2, 1).Text = "7"
            sembilan(2, 2).Text = "9"
            sembilan(2, 3).Text = "2"
            sembilan(2, 4).Text = "8"
            sembilan(2, 5).Text = "5"
            sembilan(2, 6).Text = "4"
            sembilan(2, 7).Text = "6"
            sembilan(2, 8).Text = "1"
            sembilan(3, 0).Text = "5"
            sembilan(3, 1).Text = "4"
            sembilan(3, 2).Text = "8"
            sembilan(3, 3).Text = "9"
            sembilan(3, 4).Text = "5"
            sembilan(3, 5).Text = "7"
            sembilan(3, 6).Text = "1"
            sembilan(3, 7).Text = "3"
            sembilan(3, 8).Text = "2"
            sembilan(4, 0).Text = "7"
            sembilan(4, 1).Text = "5"
            sembilan(4, 2).Text = "3"
            sembilan(4, 3).Text = "6"
            sembilan(4, 4).Text = "1"
            sembilan(4, 5).Text = "2"
            sembilan(4, 6).Text = "9"
            sembilan(4, 7).Text = "4"
            sembilan(4, 8).Text = "8"
            sembilan(5, 0).Text = "9"
            sembilan(5, 1).Text = "1"
            sembilan(5, 2).Text = "2"
            sembilan(5, 3).Text = "8"
            sembilan(5, 4).Text = "4"
            sembilan(5, 5).Text = "3"
            sembilan(5, 6).Text = "6"
            sembilan(5, 7).Text = "5"
            sembilan(5, 8).Text = "7"
            sembilan(6, 0).Text = "5"
            sembilan(6, 1).Text = "2"
            sembilan(6, 2).Text = "4"
            sembilan(6, 3).Text = "7"
            sembilan(6, 4).Text = "6"
            sembilan(6, 5).Text = "8"
            sembilan(6, 6).Text = "3"
            sembilan(6, 7).Text = "1"
            sembilan(6, 8).Text = "9"
            sembilan(7, 0).Text = "8"
            sembilan(7, 1).Text = "3"
            sembilan(7, 2).Text = "6"
            sembilan(7, 3).Text = "1"
            sembilan(7, 4).Text = "2"
            sembilan(7, 5).Text = "9"
            sembilan(7, 6).Text = "5"
            sembilan(7, 7).Text = "7"
            sembilan(7, 8).Text = "4"
            sembilan(8, 0).Text = "1"
            sembilan(8, 1).Text = "9"
            sembilan(8, 2).Text = "7"
            sembilan(8, 3).Text = "5"
            sembilan(8, 4).Text = "3"
            sembilan(8, 5).Text = "4"
            sembilan(8, 6).Text = "2"
            sembilan(8, 7).Text = "8"
            sembilan(8, 8).Text = "6"

        ElseIf sembilanQQ = 9 Then
            sembilan(0, 0).Text = "1"
            sembilan(0, 1).Text = "4"
            sembilan(0, 2).Text = "5"
            sembilan(0, 3).Text = "2"
            sembilan(0, 4).Text = "3"
            sembilan(0, 5).Text = "6"
            sembilan(0, 6).Text = "7"
            sembilan(0, 7).Text = "8"
            sembilan(0, 8).Text = "9"
            sembilan(1, 0).Text = "6"
            sembilan(1, 1).Text = "2"
            sembilan(1, 2).Text = "7"
            sembilan(1, 3).Text = "1"
            sembilan(1, 4).Text = "8"
            sembilan(1, 5).Text = "9"
            sembilan(1, 6).Text = "3"
            sembilan(1, 7).Text = "4"
            sembilan(1, 8).Text = "5"
            sembilan(2, 0).Text = "8"
            sembilan(2, 1).Text = "9"
            sembilan(2, 2).Text = "3"
            sembilan(2, 3).Text = "4"
            sembilan(2, 4).Text = "5"
            sembilan(2, 5).Text = "7"
            sembilan(2, 6).Text = "1"
            sembilan(2, 7).Text = "2"
            sembilan(2, 8).Text = "6"
            sembilan(3, 0).Text = "2"
            sembilan(3, 1).Text = "1"
            sembilan(3, 2).Text = "4"
            sembilan(3, 3).Text = "3"
            sembilan(3, 4).Text = "6"
            sembilan(3, 5).Text = "5"
            sembilan(3, 6).Text = "8"
            sembilan(3, 7).Text = "9"
            sembilan(3, 8).Text = "7"
            sembilan(4, 0).Text = "3"
            sembilan(4, 1).Text = "5"
            sembilan(4, 2).Text = "8"
            sembilan(4, 3).Text = "7"
            sembilan(4, 4).Text = "9"
            sembilan(4, 5).Text = "1"
            sembilan(4, 6).Text = "2"
            sembilan(4, 7).Text = "6"
            sembilan(4, 8).Text = "4"
            sembilan(5, 0).Text = "7"
            sembilan(5, 1).Text = "6"
            sembilan(5, 2).Text = "9"
            sembilan(5, 3).Text = "8"
            sembilan(5, 4).Text = "2"
            sembilan(5, 5).Text = "4"
            sembilan(5, 6).Text = "5"
            sembilan(5, 7).Text = "1"
            sembilan(5, 8).Text = "3"
            sembilan(6, 0).Text = "4"
            sembilan(6, 1).Text = "3"
            sembilan(6, 2).Text = "1"
            sembilan(6, 3).Text = "6"
            sembilan(6, 4).Text = "7"
            sembilan(6, 5).Text = "2"
            sembilan(6, 6).Text = "9"
            sembilan(6, 7).Text = "5"
            sembilan(6, 8).Text = "8"
            sembilan(7, 0).Text = "5"
            sembilan(7, 1).Text = "7"
            sembilan(7, 2).Text = "2"
            sembilan(7, 3).Text = "9"
            sembilan(7, 4).Text = "4"
            sembilan(7, 5).Text = "8"
            sembilan(7, 6).Text = "6"
            sembilan(7, 7).Text = "3"
            sembilan(7, 8).Text = "1"
            sembilan(8, 0).Text = "9"
            sembilan(8, 1).Text = "8"
            sembilan(8, 2).Text = "6"
            sembilan(8, 3).Text = "5"
            sembilan(8, 4).Text = "1"
            sembilan(8, 5).Text = "3"
            sembilan(8, 6).Text = "4"
            sembilan(8, 7).Text = "7"
            sembilan(8, 8).Text = "2"

        ElseIf sembilanQQ = 10 Then
            sembilan(0, 0).Text = "3"
            sembilan(0, 1).Text = "6"
            sembilan(0, 2).Text = "5"
            sembilan(0, 3).Text = "7"
            sembilan(0, 4).Text = "4"
            sembilan(0, 5).Text = "2"
            sembilan(0, 6).Text = "8"
            sembilan(0, 7).Text = "1"
            sembilan(0, 8).Text = "9"
            sembilan(1, 0).Text = "8"
            sembilan(1, 1).Text = "4"
            sembilan(1, 2).Text = "2"
            sembilan(1, 3).Text = "3"
            sembilan(1, 4).Text = "1"
            sembilan(1, 5).Text = "9"
            sembilan(1, 6).Text = "7"
            sembilan(1, 7).Text = "5"
            sembilan(1, 8).Text = "6"
            sembilan(2, 0).Text = "9"
            sembilan(2, 1).Text = "7"
            sembilan(2, 2).Text = "1"
            sembilan(2, 3).Text = "8"
            sembilan(2, 4).Text = "5"
            sembilan(2, 5).Text = "6"
            sembilan(2, 6).Text = "3"
            sembilan(2, 7).Text = "4"
            sembilan(2, 8).Text = "2"
            sembilan(3, 0).Text = "4"
            sembilan(3, 1).Text = "5"
            sembilan(3, 2).Text = "6"
            sembilan(3, 3).Text = "9"
            sembilan(3, 4).Text = "7"
            sembilan(3, 5).Text = "8"
            sembilan(3, 6).Text = "1"
            sembilan(3, 7).Text = "2"
            sembilan(3, 8).Text = "3"
            sembilan(4, 0).Text = "1"
            sembilan(4, 1).Text = "3"
            sembilan(4, 2).Text = "9"
            sembilan(4, 3).Text = "4"
            sembilan(4, 4).Text = "2"
            sembilan(4, 5).Text = "5"
            sembilan(4, 6).Text = "6"
            sembilan(4, 7).Text = "7"
            sembilan(4, 8).Text = "8"
            sembilan(5, 0).Text = "2"
            sembilan(5, 1).Text = "8"
            sembilan(5, 2).Text = "7"
            sembilan(5, 3).Text = "6"
            sembilan(5, 4).Text = "3"
            sembilan(5, 5).Text = "1"
            sembilan(5, 6).Text = "5"
            sembilan(5, 7).Text = "9"
            sembilan(5, 8).Text = "4"
            sembilan(6, 0).Text = "6"
            sembilan(6, 1).Text = "1"
            sembilan(6, 2).Text = "4"
            sembilan(6, 3).Text = "5"
            sembilan(6, 4).Text = "9"
            sembilan(6, 5).Text = "3"
            sembilan(6, 6).Text = "2"
            sembilan(6, 7).Text = "8"
            sembilan(6, 8).Text = "7"
            sembilan(7, 0).Text = "5"
            sembilan(7, 1).Text = "9"
            sembilan(7, 2).Text = "3"
            sembilan(7, 3).Text = "2"
            sembilan(7, 4).Text = "8"
            sembilan(7, 5).Text = "7"
            sembilan(7, 6).Text = "4"
            sembilan(7, 7).Text = "6"
            sembilan(7, 8).Text = "1"
            sembilan(8, 0).Text = "7"
            sembilan(8, 1).Text = "2"
            sembilan(8, 2).Text = "8"
            sembilan(8, 3).Text = "1"
            sembilan(8, 4).Text = "6"
            sembilan(8, 5).Text = "4"
            sembilan(8, 6).Text = "9"
            sembilan(8, 7).Text = "3"
            sembilan(8, 8).Text = "5"
        End If


        For i = 0 To 8
            For y = 0 To 8
                soalsembilan(i, y) = sembilan(i, y).Text
            Next
        Next

        If level = 0 Then
            numbelow = 37
            numupper = 41
        ElseIf level = 1 Then
            numbelow = 31
            numupper = 35
        ElseIf level = 2 Then
            numbelow = 25
            numupper = 28
        End If
        counthilang = 0
        While counthilang <= numbelow
            For i = 0 To 8
                For y = 0 To 8
                    hilang = Rnd() * 1

                    If hilang = 0 Then
                        If sembilan(i, y).Text <> "" Then
                            sembilan(i, y).Text = ""
                        End If
                    Else
                        counthilang += 1
                    End If
                    If sembilan(i, y).Text <> "" Then
                        sembilan(i, y).Enabled = False
                    Else
                        sembilan(i, y).Enabled = True
                    End If
                    If counthilang >= numupper Then
                        counthilang = 0
                        For j = 0 To 8
                            For k = 0 To 8
                                sembilan(j, k).Text = soalsembilan(j, k)
                            Next
                        Next
                        i = 100
                        y = 100
                    End If
                Next
            Next
        End While

    End Sub

    Private Sub Bttn_close9_Click(sender As Object, e As EventArgs) Handles Bttn_close9.Click
        Timer1_sembilan.Enabled = False
        Me.Close()
    End Sub
        Sub isiangka(sender As Object, e As EventArgs)
            If sender.text = "" Then
                value = ""
            Else
                value = sender.text
            End If
            FORM5_TOMBOL.ShowDialog()
            sender.text = value
        End Sub

        Private Sub Bttn_Hint_Click(sender As Object, e As EventArgs) Handles Bttn_Hint.Click
            hitunghint += 1

            awal = Rnd() * 8
            akhir = Rnd() * 8
            While sembilan(awal, akhir).Text <> ""
                awal = Rnd() * 8
                akhir = Rnd() * 8
            End While
            sembilan(awal, akhir).Text = soalsembilan(awal, akhir)
        End Sub

        Private Sub Bttn_GiveUp_Click(sender As Object, e As EventArgs) Handles Bttn_GiveUp.Click
            For i = 0 To 8
                For y = 0 To 8
                    If sembilan(i, y).Text = "" Then
                        sembilan(i, y).ForeColor = Color.BlueViolet
                    ElseIf sembilan(i, y).Text <> "" Then
                        If sembilan(i, y).Text <> soalsembilan(i, y) Then
                            sembilan(i, y).ForeColor = Color.BlueViolet
                        End If
                    ElseIf sembilan(i, y).ForeColor = Color.Red Then
                        sembilan(i, y).ForeColor = Color.BlueViolet
                    End If
                    sembilan(i, y).Text = soalsembilan(i, y)
                Next
            Next
        End Sub

    Private Sub Timer1_sembilan_Tick(sender As Object, e As EventArgs) Handles Timer1_sembilan.Tick
        a += 1
        If b >= 60 Then
            b = 0
            c += 1
        End If
        If c < 10 Then
            lbl_jam.Text = "0" & c
        Else
            lbl_jam.Text = c
        End If

        If a >= 60 Then
            a = 0
            b += 1
        End If
        If b < 10 Then
            lbl_menit.Text = "0" & b
        Else
            lbl_menit.Text = b
        End If

        If a < 10 Then
            lbl_detik.Text = "0" & a
        Else
            lbl_detik.Text = a
        End If

        waktuu = lbl_jam.Text & " : " & lbl_menit.Text & " : " & lbl_detik.Text
    End Sub
End Class